server {
    listen __SITBANK_PUBLIC_BIND_ADDRESS__:80 default_server;
    server_name _;
    return 444;
}

server {
    listen __SITBANK_PUBLIC_BIND_ADDRESS__:443 ssl http2 default_server;
    server_name _;
    ssl_reject_handshake on;
    return 444;
}
