server {
    listen 80;
    listen [::]:80;
    server_name staging-sitbank.duckdns.org;

    location / {
        proxy_pass http://127.0.0.1:5001;
        include /etc/nginx/snippets/sitbank-proxy-headers.conf;
    }
}
