from __future__ import annotations

import uuid
from dataclasses import dataclass

from sqlalchemy import Column, Integer, MetaData, String, Table, bindparam, create_engine, select, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import DBAPIError


PRIVILEGE_DENIED_SQLSTATE = "42501"
KNOWN_EXTENSION_PROBES = ("pg_trgm", "hstore", "citext", "pgcrypto")


@dataclass(frozen=True)
class RuntimePrivilegeVerification:
    runtime_role: str
    migration_role: str
    probe_table: str
    extension_probe: str


def verify_runtime_database_privileges(
    *,
    runtime_url: str,
    migration_url: str,
    schema: str = "public",
) -> RuntimePrivilegeVerification:
    if not migration_url:
        raise RuntimeError("DATABASE_MIGRATION_URL is required for runtime privilege verification")
    if runtime_url == migration_url:
        raise RuntimeError("DATABASE_URL and DATABASE_MIGRATION_URL must use different roles")
    if not _is_identifier(schema):
        raise RuntimeError("Schema name is not a safe PostgreSQL identifier")

    runtime_engine = create_engine(runtime_url)
    migration_engine = create_engine(migration_url)
    probe_table = f"sitbank_privilege_probe_{uuid.uuid4().hex}"
    create_probe_table = (
        f'CREATE TABLE {_quote_identifier(schema)}.{_quote_identifier(probe_table)} '
        "(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marker text NOT NULL)"
    )

    try:
        with migration_engine.begin() as migration_connection:
            migration_role = str(
                migration_connection.execute(text("SELECT current_user")).scalar_one()
            )
            migration_connection.execute(text(create_probe_table))

        try:
            with runtime_engine.connect() as runtime_connection:
                runtime_role = str(runtime_connection.execute(text("SELECT current_user")).scalar_one())
                if runtime_role == migration_role:
                    raise RuntimeError("Runtime and migration connections are using the same role")
                _assert_runtime_role_owns_no_schema_objects(runtime_connection, runtime_role, schema)
                _assert_probe_table_owner(
                    runtime_connection,
                    schema=schema,
                    probe_table=probe_table,
                    expected_owner=migration_role,
                )
                _assert_runtime_dml_allowed(runtime_connection, schema=schema, probe_table=probe_table)
                _expect_privilege_denied(
                    runtime_connection,
                    f'ALTER TABLE {_quote_identifier(schema)}.{_quote_identifier(probe_table)} '
                    "ADD COLUMN should_not_exist integer",
                    "ALTER TABLE",
                )
                _expect_privilege_denied(
                    runtime_connection,
                    f'DROP TABLE {_quote_identifier(schema)}.{_quote_identifier(probe_table)}',
                    "DROP TABLE",
                )
                _expect_privilege_denied(
                    runtime_connection,
                    f'CREATE TABLE {_quote_identifier(schema)}.{_quote_identifier(probe_table)}_create '
                    "(id integer)",
                    "CREATE TABLE",
                )
                extension_probe = _select_extension_probe(runtime_connection)
                _expect_privilege_denied(
                    runtime_connection,
                    f"CREATE EXTENSION {_quote_identifier(extension_probe)}",
                    "CREATE EXTENSION",
                )
        finally:
            _drop_probe_table(migration_engine, schema=schema, probe_table=probe_table)
    finally:
        runtime_engine.dispose()
        migration_engine.dispose()

    return RuntimePrivilegeVerification(
        runtime_role=runtime_role,
        migration_role=migration_role,
        probe_table=probe_table,
        extension_probe=extension_probe,
    )


def _assert_runtime_role_owns_no_schema_objects(connection, runtime_role: str, schema: str) -> None:
    database_owner = connection.execute(
        text("SELECT pg_get_userbyid(datdba) FROM pg_database WHERE datname = current_database()")
    ).scalar_one()
    if database_owner == runtime_role:
        raise RuntimeError("Runtime role owns the current database")

    can_create_database_objects = connection.execute(
        text("SELECT has_database_privilege(current_user, current_database(), 'CREATE')")
    ).scalar_one()
    if can_create_database_objects:
        raise RuntimeError("Runtime role has CREATE privilege on the current database")

    schema_owner = connection.execute(
        text(
            """
            SELECT pg_get_userbyid(nspowner)
            FROM pg_namespace
            WHERE nspname = :schema
            """
        ),
        {"schema": schema},
    ).scalar_one()
    if schema_owner == runtime_role:
        raise RuntimeError(f"Runtime role owns schema {schema}")

    rows = connection.execute(
        text(
            """
            SELECT c.relname
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_roles r ON r.oid = c.relowner
            WHERE n.nspname = :schema
              AND r.rolname = :runtime_role
              AND c.relkind IN ('r', 'p', 'S', 'v', 'm')
              AND c.relpersistence <> 't'
            ORDER BY c.relname
            """
        ),
        {"schema": schema, "runtime_role": runtime_role},
    ).all()
    if rows:
        owned = ", ".join(row.relname for row in rows[:5])
        raise RuntimeError(f"Runtime role owns schema objects: {owned}")

    can_create_schema = connection.execute(
        text("SELECT has_schema_privilege(current_user, :schema, 'CREATE')"),
        {"schema": schema},
    ).scalar_one()
    if can_create_schema:
        raise RuntimeError(f"Runtime role has CREATE privilege on schema {schema}")

    extensions = connection.execute(
        text(
            """
            SELECT e.extname
            FROM pg_extension e
            JOIN pg_roles r ON r.oid = e.extowner
            WHERE r.rolname = :runtime_role
            ORDER BY e.extname
            """
        ),
        {"runtime_role": runtime_role},
    ).all()
    if extensions:
        owned = ", ".join(row.extname for row in extensions[:5])
        raise RuntimeError(f"Runtime role owns PostgreSQL extensions: {owned}")


def _assert_probe_table_owner(connection, *, schema: str, probe_table: str, expected_owner: str) -> None:
    owner = connection.execute(
        text(
            """
            SELECT pg_get_userbyid(c.relowner)
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = :schema AND c.relname = :probe_table
            """
        ),
        {"schema": schema, "probe_table": probe_table},
    ).scalar_one()
    if owner != expected_owner:
        raise RuntimeError("Migration role does not own the privilege probe table")


def _assert_runtime_dml_allowed(connection, *, schema: str, probe_table: str) -> None:
    table = Table(
        probe_table,
        MetaData(),
        Column("id", Integer),
        Column("marker", String),
        schema=schema,
    )
    if connection.in_transaction():
        connection.rollback()
    with connection.begin():
        inserted_id = connection.execute(
            table.insert().values(marker="initial").returning(table.c.id)
        ).scalar_one()
        selected_marker = connection.execute(
            select(table.c.marker).where(table.c.id == inserted_id)
        ).scalar_one()
        if selected_marker != "initial":
            raise RuntimeError("Runtime role could not read back inserted probe data")
        connection.execute(table.update().where(table.c.id == inserted_id).values(marker="updated"))
        connection.execute(table.delete().where(table.c.id == inserted_id))


def _expect_privilege_denied(connection, statement: str, label: str) -> None:
    if connection.in_transaction():
        connection.rollback()
    transaction = connection.begin()
    try:
        connection.execute(text(statement))
    except DBAPIError as exc:
        transaction.rollback()
        if _sqlstate(exc) != PRIVILEGE_DENIED_SQLSTATE:
            raise RuntimeError(f"{label} failed with unexpected SQLSTATE {_sqlstate(exc)}") from exc
        return
    else:
        transaction.rollback()
        raise RuntimeError(f"Runtime role unexpectedly succeeded at {label}")


def _select_extension_probe(connection) -> str:
    rows = connection.execute(
        text(
            """
            SELECT name
            FROM pg_available_extensions
            WHERE installed_version IS NULL AND name IN :extension_names
            """
        ).bindparams(bindparam("extension_names", expanding=True)),
        {"extension_names": KNOWN_EXTENSION_PROBES},
    ).scalars()
    available = set(rows)
    for extension in KNOWN_EXTENSION_PROBES:
        if extension in available:
            return extension
    raise RuntimeError("No uninstalled known PostgreSQL extension is available to test")


def _drop_probe_table(engine: Engine, *, schema: str, probe_table: str) -> None:
    with engine.begin() as connection:
        connection.execute(
            text(
                f"DROP TABLE IF EXISTS {_quote_identifier(schema)}."
                f"{_quote_identifier(probe_table)}"
            )
        )
        connection.execute(
            text(
                f"DROP TABLE IF EXISTS {_quote_identifier(schema)}."
                f"{_quote_identifier(probe_table)}_create"
            )
        )


def _sqlstate(exc: DBAPIError) -> str:
    return str(getattr(exc.orig, "pgcode", "") or getattr(exc.orig, "sqlstate", "") or "")


def _quote_identifier(identifier: str) -> str:
    if not _is_identifier(identifier):
        raise RuntimeError("Unsafe PostgreSQL identifier")
    return f'"{identifier}"'


def _is_identifier(value: str) -> bool:
    return bool(value) and value.replace("_", "a").isalnum() and value[0].isalpha()
